### ISSUE TITLE
USER STORY Edit a travel story

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#13]
As a **user** I can **edit a travel story that I have created** so that **I can make changes after it was created and decide what I want to share with other users**.

Tasks:
- [x] Create edit button for each travel story.
- [x] Create edit form and ternary to check if user is owner
- [x] Use hooks and handlers to redirect, handle changes and prefill form
- [x] Test form functionality

Acceptance criteria:
- A user that is logged in needs to be able to edit a travel story that it has created.
- A user can only edit it´s own stories.
