### ISSUE TITLE
USER STORY View the top 5 most liked stories

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#15]
As a **user** I can **view the top 5 most liked stories** so that **I know which stories are the most popular**.

Tasks:
- [x] Create components for popular story section, popular story  data and popular story page to view a single popular story.
- [x] Add ternaries to show popular stories or asset spinner and with different layout depending on device
- [x] Add css styling

Acceptance criteria:
- All users needs to be able to see the most popular stories.
- The most popular stories should be displayed with miage, title and destination.
