### ISSUE TITLE
USER STORY Edit a comment

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#16]
As a **user** I can **edit a travel story comment that I have created** so that **I can make changes after it was created and decide what I want to share with other users**.

Tasks:
- [x] Create edit button for each comment.
- [x] Create edit form and add ternary to check comment owner
- [x] Use hooks and handlers to redirect, handle changes and prefill form
- [x] Test form functionality
- [x] Add css styling

Acceptance criteria:
- A user that is logged in needs to be able to edit a travel story comment that it has created.
- A user can only edit it´s own comments.
