### ISSUE TITLE
USER STORY View a profile and the stories made by the profile owner 

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#17]
As a **user** I can **view my and other users profile and all my and their created stories** so that **I can keep track of my own profile content and discover all stories made by a user**.

Tasks:
- [x] Create component and route
- [x] Fetch and display data - use hooks and handlers
- [x] Add ternary condition to check if user has any stories
- [x] Add styling
- [x] Add loading image
- [x] Add infinate scroll functionality

Acceptance criteria:
- Users must be able to see all their created stories in a list, to keep track of them.
- Users must be able to view their profile, to see what they are sharing with others.
- The list of stories should show the most recent first.
