### ISSUE TITLE
USER STORY Edit my profile

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#18]
As a **user** I can **edit my profile** so that **I can decide what I want to share with other users**.

Tasks:
- [x] Create edit dropdown button and menu.
- [x] Create components and routes
- [x] Create edit forms with ternaries to check profile owner
- [x] Use hooks and handlers to redirect, handle changes and prefill form
- [x] Test form functionality
- [x] Add css styling
- [x] Add responsivness

Acceptance criteria:
- A user that is logged in needs to be able to edit/update its profile.
- A user can only edit its own profile.
