### ISSUE TITLE
USER STORY View bucket list items (destinations)

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#23]
As a **user** I can **view my bucket list items (destinations)** so that **I can see what trips I dream about taking and activites to do on the trips**.

Tasks:
- [x] Create components and routes
- [x] Fetch and display data - use hooks and handlers
- [x] Add filter and sorting 
- [x] Add spinner and infinate scroll functionality

Acceptance criteria:
- Users must be able to see a list of destinations they want to visit. 
- The list of destinations should be ordered according to the user´s priority. Highest priority at the top.
