### ISSUE TITLE
USER STORY View all travel stories

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#25]
As a **user** I can **view all shared travel stories** so that **I can be inspired and get ideas about where I want to travel**.

Tasks:
- [x] Create components and route
- [x] Fetch and display data - use hooks and ternaries
- [x] Add loading spinner
- [x] Add infinate scroll functionality

Acceptance criteria:
- The home page of the site needs to show all travel stories.
- All users of the site (logged in or not) can see all the travel stories.
- The most resent travel stories should be displayed first/at the top, then keep scrolling to see all stories.
- Users should be informed of when the API is working on getting the request data.
