### ISSUE TITLE
USER STORY View comments

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#27]
As a **user** I can **view a travel story comment** so that **I can read about what other users think about a story**.

Tasks:
- [x] Create components and route
- [x] Fetch and display data - use hooks and ternaries
- [x] Fix bug - comments_count not showing

Acceptance criteria:
- All users of the site (logged in or not) can see all the comments on a travel story.
- The most resent comments should be displayed first/at the top.
