### ISSUE TITLE
USER STORY Navigation - Navbar

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#29]
As a **user** I can **use a navbar from every page** so that **I can reach all pages of the site**.

Tasks:
- [x] Add a navbar with logo.
- [x] Add routing functionality
- [x] Create hook
- [x] Style navbar - add logo and colors

Acceptance criteria:
- The navbar must be a part of all pages of the site.
- The navbar must contain a logo which is linked to the home page.
