### ISSUE TITLE
USER STORY Authentication - Sign In

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#33]
As a **user** I can **sign in to my account** so that **I can add stories, comment, like, save and create a bucket list**.

Tasks:
- [x] Create sign in form
- [x] Add hooks and handlers
- [x] Connect to API
- [x] Add error messages
- [x] Add responsivness
- [x] Add css styling
- [x] Test form functionality

Acceptance criteria:
- Form input must be validated
- The form must be connected to the API so that data can be fetched.
- The form must be simple and easy to understand so that users can sign up without any problems.
