### ISSUE TITLE
USER STORY View a travel story

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#4]
As a **user** I can **view a travel story** so that **I can get all details about a story**.

Tasks:
- [x] Create component that holds all story data and can be used to render all stories in a list.
- [x] Add routes and functions
- [x] Fetch and display data - use hooks and handlers
- [x] Add css styling

Acceptance criteria:
- Users must be able to view a travel story and data/information regarding it.
