### ISSUE TITLE
USER STORY Like a travel story

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#5]
As a **user** I can **like a travel story** so that **I can show to the creater/owner of the post that it interests me**.

Tasks:
- [x] Create component and function 
- [x] Connect to travel story
- [x] Add ternary condition
- [x] Add styling 

Acceptance criteria:
- All logged in users must be able to like a tavel story. Only logged in users can like a story.
- The user can not like it´s own stories.
