### ISSUE TITLE
USER STORY Save a travel story

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#6]
As a **user** I can **save a travel story** so that **I don´t forget my favorite stories and can return to them whenever I want to**.

Tasks:
- [x] Create component and function 
- [x] Add filter so that only stories saved by the user is shown
- [x] Connect to travel story
- [x] Add ternary condition
- [x] Add styling 

Acceptance criteria:
- All logged in users must be able to save a tavel story. Only logged in users can save.
- The user can not save it´s own stories.
