### ISSUE TITLE
USER STORY Create a travel story

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#7]
As a **user** I can **create a travel story** so that **I can share my adventures and experiances with others**.

Tasks:
- [x] Create travel story form
- [x] Add ternary to let users change the selected image.
- [x] Create asset component that can be reused
- [x] Add handlers to handle post to API
- [x] Add styling to the form

Acceptance criteria:
- All logged in users must be able to create a travel story that all user (even those not logged in) can see.
- Form should have a default image.
- The user must be able to change the selected image when still in the form (i.e. without having to submit first).
