### ISSUE TITLE
USER STORY Create a comment

### ISSUE THREAD

**Issue by sarasm93** [sarasm93/travel-stories2#8]
As a **user** I can **create a travel story comment** so that **I can be in contact with other users and give feedback on stories that interests me**.

Tasks:
- [x] Create comment form
- [x] Add handlers to handle post to API
- [x] Add styling to the form

Acceptance criteria:
- All logged in users must be able to create a travel story comment.
- A comment should contain, apart from the content, at least an image and username of the owner.
